#!/bin/sh
# this makes cursor-up keys and similar work.
setxkbmap -rules evdev -model evdev
#setxkbmap -layout de -rules evdev -model evdev -variant nodeadkeys

# this will automatically start lxde. if you do not want this, start xterm oslt
exec startlxde
