#!/bin/sh
[ -z "$CONFIG" ] && CONFIG=./config
source "$CONFIG"
export H="$PWD"

if [ -z "$R" ] ; then
	echo 'no R environment var set, your config is broken'
	exit 1
fi

mkdir -p "$R"/src/tarballs

if [ ! -z "$SUPER" ] ; then
	CHROOT=./super_chroot
	if [ ! -x "$CHROOT" ] ; then
		printf "super_chroot binary not found, compile KEEP/super_chroot.c\n"
		printf "musl-gcc KEEP/super_chroot.c -o super_chroot\n"
		exit 1
	fi
else

	uid="$(id -u)"
	if [ "$uid" != "0" ]; then
	    printf -- "need to be root. please enter password.\n"
	    su -c "$0"
	    exit $?
	fi


	mount --rbind /dev "$R"/dev
	mount --rbind /proc "$R"/proc
	mount --bind "$C" "$R"/src/tarballs

	CHROOT=chroot
fi

echo "Entering chroot..."
"$CHROOT" "$R" /bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w$ ' \
    /bin/sh --login

tryumount() {
	dest="$1"
	if ! umount "$dest" 2>/dev/null; then
		echo "unmount failure ($dest), retrying in 1 sec..."
		sleep 1
		umount -f "$dest"
	fi
}

if [ -z "$SUPER" ] ; then
	tryumount "$R"/src/tarballs
	tryumount "$R"/dev/pts
	tryumount "$R"/dev/shm
	tryumount "$R"/dev
	tryumount "$R"/proc
fi

#echo empty line so we get a proper prompt back
echo

