#!/bin/sh
source ./config
if [ -z "$R" ] ; then
	echo 'no environment vars set, did you run . config first ?'
	exit 1
fi

uid="$(id -u)"
if [ "$uid" != "0" ]; then
    printf -- "need to be root. please enter password.\n"
    su -c "$0"
    exit $?
fi

export H="$PWD"

mkdir -p "$R"/src/tarballs

mount --rbind /dev "$R"/dev
mount --rbind /proc "$R"/proc
mount --bind "$C" "$R"/src/tarballs

echo "Entering chroot..."
chroot "$R" /bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w$ ' \
    /bin/sh --login

tryumount() {
	dest="$1"
	if ! umount "$dest" 2>/dev/null; then
		echo "unmount failure ($dest), retrying in 1 sec..."
		sleep 1
		umount -f "$dest"
	fi
}

tryumount "$R"/src/tarballs
tryumount "$R"/dev/pts
tryumount "$R"/dev/shm
tryumount "$R"/dev
tryumount "$R"/proc

#echo empty line so we get a proper prompt back
echo

