#!/bin/sh
SRVDIR=/var/run/dovecot/login
if [ ! -d "$SRVDIR" ] ; then
  busybox addgroup -S dovecot
  busybox adduser -h "$SRVDIR" -s /bin/nologin -S -D -G dovecot dovecot
  busybox addgroup -S dovecot
  busybox adduser -h "$SRVDIR" -s /bin/nologin -S -D -G dovenull dovenull
fi
if [ ! -f /etc/dovecot/dovecot.key ] ; then
   su -s /bin/sh - dovecot -c \
      "openssl req -new -x509 -days 3650 -nodes -out /etc/dovecot/dovecot.crt \
      -subj '/C=US/ST=Oregon/L=Portland/CN=invalid.org' \
      -keyout /etc/dovecot/dovecot.key && chmod o= /etc/dovecot/dovecot.key" || exit 1
fi
[ "$1" = "--prereqs" ] && exit 0

exec dovecot -F
