#!/bin/sh
DOVECOT_HOME=/var/run/dovecot/login
if [ ! -d "$DOVECOT_HOME" ] ; then
  mkdir -p "$(dirname $DOVECOT_HOME)"
  busybox addgroup -S dovecot
  busybox adduser -h "$DOVECOT_HOME" -s /bin/nologin -S -D -G dovecot dovecot
  busybox addgroup -S dovenull
  busybox adduser -h "$DOVECOT_HOME" -s /bin/nologin -S -D -G dovenull dovenull
  chown -R dovecot /var/lib/dovecot
  chgrp -R dovecot /var/lib/dovecot
fi
if [ ! -f /etc/dovecot/dovecot.key ] ; then
  openssl req -new -x509 -days 3650 -nodes -out /etc/dovecot/dovecot.crt \
     -subj '/C=US/ST=Oregon/L=Portland/CN=invalid.org' \
     -keyout /etc/dovecot/dovecot.key && chmod o= /etc/dovecot/dovecot.key || exit 1
  chgrp -R dovecot /etc/dovecot/
  chmod -R 640 /etc/dovecot/
fi
[ "$1" = "--prereqs" ] && exit 0
exec dovecot -F 2>&1
