#!/bin/sh
SRVDIR=/var/spool/postfix
if [ ! -d "$SRVDIR" ] ; then
  busybox addgroup -S postfix
  busybox addgroup -S postdrop
  busybox adduser -h "$SRVDIR" -s /bin/false -S -D -G postfix postfix
fi
if [ ! -f /etc/postfix/postfix.key ] ; then
   su -s /bin/sh - postfix -c \
      "openssl req -new -x509 -days 3650 -nodes -out /etc/postfix/postfix.crt \
      -subj '/C=US/ST=Oregon/L=Portland/CN=invalid.org' \
      -keyout /etc/postfix/postfix.key && chmod o= /etc/postfix/postfix.key" || exit 1
fi
postmap /etc/postfix/virtual
[ ! -f /etc/aliases ] && touch /etc/aliases && newaliases
[ "$1" = "--prereqs" ] && exit 0

exec /lib/postfix/master -d
