#!/bin/sh
TORHOME=/var/run/tor
if [ ! -d "$TORHOME" ] ; then
  mkdir -p "$(dirname $TORHOME)"
  busybox addgroup -S tor && busybox adduser -h "$TORHOME" -S -G tor tor
  su -s /bin/sh - tor -c "mkdir -p env ; echo $TORHOME > env/HOME"
fi
[ "$1" = "--prereqs" ] && exit 0
bindrwdir() {
  dir="$1"
  user=$2
  group=$3
  if ! touch "$dir"/test; then
    if [ ! -e /mnt/sabotagerw/"$dir" ]; then
      mkdir -p /mnt/sabotagerw/"$dir"
      cp -a "$dir"/* /mnt/sabotagerw/"$dir"
      chown -R $user /mnt/sabotagerw/"$dir"
      chgrp -R $group /mnt/sabotagerw/"$dir"
    fi
    mount --bind /mnt/sabotagerw/"$dir" "$dir"
  else
    rm "$dir"/test
  fi
}
bindrwdir $TORHOME tor tor

exec chpst -e $TORHOME/env -u tor tor 2>&1
