#!/bin/sh
filesize='63408'
sha512='d0e22f1d2fbce4af80f9d0ad9f540d41246c2f605f8d1e971c6266247fe41231e00419ddba2cb977a5f7813d977124b81b00738727f7d13055b2acccfeedde46'
filename="$C"/butch-0.1.3.tar.bz2

if [ -z "$BUTCH_BIN" ] ; then

tarxf http://mirror.wzff.de/butch/ butch-0.1.3 .tar.bz2 butch

read sz _ <<EOF
$(du -b "$filename")
EOF

if [ "$sz" != "$filesize" ]; then
    printf -- "error: build-butch: wrong filesize. got: %d expected: %d\n" "$sz" "$filesize"
    exit 1
fi

read sha _ <<EOF
$(sha512sum "$filename")
EOF

if [ "$sha" != "$sha512" ]; then
    printf -- "error: build-butch: hash doesn't match.\n"
    exit 1
fi

# this speeds up compilation a bit
echo "CFLAGS=-O0" > butch/config.mak

# if on arm or mips, we only use one build thread to not exhaust memory
[ "$A" = "arm" ] || [ "$A" = "mips" ] && sed -i \
  's@#define NUM_BUILD_THREADS 2@#define NUM_BUILD_THREADS 1@' butch/butch.c

./build.sh
BUTCH_BIN=butch/butch

fi

cp "$BUTCH_BIN" "$S"/butch.bin

