#!/bin/sh
filesize='62924'
sha512='61552086768fe81462566af09c9d42f6c20d546a18a9ef12ad68aa486a4c9bb0be16048686c86cbb6f9bf9ce71bbc948a8866ba7b3fa216c0f09090312c6c881'
filename="$S"/butch-0.1.2.tar.bz2

if [ -z "$BUTCH_BIN" ] ; then

tarxf http://mirror.wzff.de/butch/ butch-0.1.2 .tar.bz2 butch

read sz _ <<EOF
$(du -b "$filename")
EOF

if [ "$sz" != "$filesize" ]; then
    printf -- "error: build-butch: wrong filesize. got: %d expected: %d\n" "$sz" "$filesize"
    exit 1
fi

read sha _ <<EOF
$(sha512sum "$filename")
EOF

if [ "$sha" != "$sha512" ]; then
    printf -- "error: build-butch: hash doesn't match.\n"
    exit 1
fi

# this speeds up compilation a bit
echo "CFLAGS=-O0" > butch/config.mak

# if on arm or mips, we only use one build thread to not exhaust memory
[ "$A" = "arm" ] || [ "$A" = "mips" ] && sed -i \
  's@#define NUM_BUILD_THREADS 2@#define NUM_BUILD_THREADS 1@' butch/butch.c

./build.sh
BUTCH_BIN=butch/butch
# copy tarball ...
cp "$filename" "$C"/

fi

cp "$BUTCH_BIN" "$S"/butch.bin

