#!/bin/sh
MYDIR=$(dirname "$(readlink -f "$0")")
export H="$MYDIR/.."
source "$H"/config

if [ -z "$R" ] ; then
	echo "error sourcing config" >&2
	exit 1
fi

cp -r "$H"/pkg "$R"/src/
cp -r "$H"/KEEP "$R"/src/

