#!/bin/sh

libc_prefix="PPPP/"
ldso_pathname="PPPP/lib/ld-musl-AAAA.so.1"
gcc=rawcc
libc_lib=$libc_prefix/lib
libc_inc=$libc_prefix/include
libc_crt="$libc_lib/crt1.o"
libc_start="$libc_lib/crti.o"
libc_end="$libc_lib/crtn.o"

tmp_specs=$HOME/.specs.tmp.$$
printf '
*link_libgcc:
-L%s

*libgcc:
libgcc.a%%s %%:if-exists(libgcc_eh.a%%s)

*cc1:
%%(cc1_cpu)

*startfile:
%%{!shared: %s} %s %s crtbegin.o%%s

*endfile:
crtend.o%%s %s

*esp_link:

*esp_options:

*esp_cpp_options:

' \
 "$libc_lib" "$libc_crt" "$libc_start" "$libc_end" > "$tmp_specs" || exit 1

exec 3<"$tmp_specs"
rm -f "$tmp_specs"

exec "$gcc" -Werror-implicit-function-declaration -specs=/proc/self/fd/3 -nostdinc -isystem "$libc_inc" \
 "$@" -Wl,-dynamic-linker,"$ldso_pathname" -Wl,-nostdlib

